export const auditActions = {
  recordCreate: "record.create",
  recordUpdate: "record.update",
  recordDelete: "record.delete",
  recordApprove: "record.approve",
  recordPublish: "record.publish",
  recordSign: "record.sign",
  recordSend: "record.send",
  permissionAssign: "permission.assign",
  permissionRevoke: "permission.revoke",
  permissionRoleCreate: "permission.role.create",
  permissionRoleUpdate: "permission.role.update",
  permissionRoleDelete: "permission.role.delete",
  permissionAssignmentCreate: "permission.assignment.create",
  permissionAssignmentRevoke: "permission.assignment.revoke",
  permissionDelegationCreate: "permission.delegation.create",
  permissionDelegationRevoke: "permission.delegation.revoke",
  aiGenerate: "ai.generate",
  aiApprove: "ai.approve",
  systemRun: "system.run",
  authSignIn: "auth.sign.in",
  authSignOut: "auth.sign.out",
  authInviteSend: "auth.invite.send",
  authInviteAccept: "auth.invite.accept",
  authEmailVerify: "auth.email.verify",
  authAccountRecover: "auth.account.recover",
  authSessionRevoke: "auth.session.revoke",
  authSecurityChange: "auth.security.change",
  franchiseCreate: "franchise.create",
  franchiseUpdate: "franchise.update",
  franchiseArchive: "franchise.archive",
  franchiseContactUpdate: "franchise.contact.update",
  franchiseAgreementGenerate: "franchise.agreement.generate",
  franchiseAgreementSubmit: "franchise.agreement.submit",
  franchiseAgreementApprove: "franchise.agreement.approve",
  franchiseAgreementVoid: "franchise.agreement.void",
  franchiseAgreementSupersede: "franchise.agreement.supersede",
  franchiseAgreementSent: "franchise.agreement.sent",
  franchiseAgreementSignerCompleted: "franchise.agreement.signer.completed",
  franchiseAgreementDeclined: "franchise.agreement.declined",
  franchiseAgreementExpired: "franchise.agreement.expired",
  franchiseAgreementCancelled: "franchise.agreement.cancelled",
  franchiseAgreementExecuted: "franchise.agreement.executed",
  franchiseAgreementResent: "franchise.agreement.resent",
  franchiseAgreementReissued: "franchise.agreement.reissued",
  franchiseDocumentUpload: "franchise.document.upload",
  franchiseDocumentVersionCreate: "franchise.document.version.create",
  franchiseDocumentArchive: "franchise.document.archive",
  franchiseDocumentView: "franchise.document.view",
  franchiseDocumentDownload: "franchise.document.download",
  franchiseInsuranceUpsert: "franchise.insurance.upsert",
  franchiseInsuranceVerify: "franchise.insurance.verify",
  franchiseInsuranceReject: "franchise.insurance.reject",
  franchiseComplianceRequirementCreate: "franchise.compliance.requirement.create",
  franchiseComplianceEvidenceSubmit: "franchise.compliance.evidence.submit",
  franchiseComplianceVerify: "franchise.compliance.verify",
  franchiseComplianceReject: "franchise.compliance.reject",
  franchiseComplianceActionCreate: "franchise.compliance.action.create",
  franchiseComplianceActionResolve: "franchise.compliance.action.resolve",
  franchiseComplianceReminderSchedule: "franchise.compliance.reminder.schedule",
  franchiseOnboardingStart: "franchise.onboarding.start",
  franchiseOnboardingTaskAssign: "franchise.onboarding.task.assign",
  franchiseOnboardingTaskComplete: "franchise.onboarding.task.complete",
  franchiseOnboardingTaskApprove: "franchise.onboarding.task.approve",
  franchiseOnboardingDateOverride: "franchise.onboarding.date.override",
  franchiseOnboardingBlockerRaise: "franchise.onboarding.blocker.raise",
  franchiseOnboardingBlockerResolve: "franchise.onboarding.blocker.resolve",
  franchiseOnboardingLaunchReady: "franchise.onboarding.launch.ready",
  franchiseOnboardingLaunchApprove: "franchise.onboarding.launch.approve",
  franchiseOnboardingLaunch: "franchise.onboarding.launch",
  publishingEditionCreate: "publishing.edition.create",
  publishingEditionUpdate: "publishing.edition.update",
  publishingEditionApprove: "publishing.edition.approve",
  publishingEditionPublish: "publishing.edition.publish",
  publishingTemplateChange: "publishing.template.change",
  publishingPageAssign: "publishing.page.assign",
  publishingContentOverride: "publishing.content.override",
  publishingPreflightOverride: "publishing.preflight.override",
  publishingPrintGenerate: "publishing.print.generate",
  publishingDigitalGenerate: "publishing.digital.generate",
  advertiserCreate: "advertiser.create",
  advertiserUpdate: "advertiser.update",
  advertiserContactUpdate: "advertiser.contact.update",
  advertiserActivityRecord: "advertiser.activity.record",
  advertiserOpportunityCreate: "advertiser.opportunity.create",
  advertiserOpportunityUpdate: "advertiser.opportunity.update",
  advertiserOpportunityStageChange: "advertiser.opportunity.stage.change",
  advertiserPricingChange: "advertiser.pricing.change",
  advertiserInventoryReserve: "advertiser.inventory.reserve",
  advertiserProposalCreate: "advertiser.proposal.create",
  advertiserProposalAccept: "advertiser.proposal.accept",
  advertiserProposalReject: "advertiser.proposal.reject",
  advertiserProposalChangeRequest: "advertiser.proposal.change.request",
  advertiserProposalViewed: "advertiser.proposal.viewed",
  advertiserBookingCreate: "advertiser.booking.create",
  advertiserBookingConfirm: "advertiser.booking.confirm",
  advertiserInvoiceCreate: "advertiser.invoice.create",
  advertiserInvoiceIssue: "advertiser.invoice.issue",
  advertiserInvoiceVoid: "advertiser.invoice.void",
  advertiserCreditIssue: "advertiser.credit.issue",
  advertiserPaymentRecord: "advertiser.payment.record",
  advertiserPaymentAllocate: "advertiser.payment.allocate",
  advertiserPaymentUnallocate: "advertiser.payment.unallocate",
  advertiserFinanceSync: "advertiser.finance.sync",
  advertiserArtworkRequest: "advertiser.artwork.request",
  advertiserArtworkSubmit: "advertiser.artwork.submit",
  advertiserArtworkPreflightFail: "advertiser.artwork.preflight.fail",
  advertiserArtworkChangesRequest: "advertiser.artwork.changes.request",
  advertiserArtworkProofIssue: "advertiser.artwork.proof.issue",
  advertiserArtworkProofApprove: "advertiser.artwork.proof.approve",
  advertiserArtworkProductionReady: "advertiser.artwork.production.ready",
  advertiserFulfilmentRecord: "advertiser.fulfilment.record",
  advertiserProofPackCreate: "advertiser.proof_pack.create",
  advertiserProofPackDeliver: "advertiser.proof_pack.deliver",
  advertiserRenewalPromptCreate: "advertiser.renewal.prompt.create",
  advertiserAnalyticsView: "advertiser.analytics.view",
  marketingAudienceContactCreate: "marketing.audience.contact.create",
  marketingAudienceContactUpdate: "marketing.audience.contact.update",
  marketingAudienceSubscribe: "marketing.audience.subscribe",
  marketingConsentRecord: "marketing.consent.record",
  marketingAudienceSuppress: "marketing.audience.suppress",
  marketingEmailTemplateCreate: "marketing.email.template.create",
  marketingEmailCampaignCreate: "marketing.email.campaign.create",
  marketingEmailCampaignApprove: "marketing.email.campaign.approve",
  marketingEmailCampaignSchedule: "marketing.email.campaign.schedule",
  marketingEmailCampaignSend: "marketing.email.campaign.send",
  marketingEmailRecipientSnapshotCreate: "marketing.email.recipient_snapshot.create",
  marketingEmailDeliveryRecord: "marketing.email.delivery.record",
  marketingNewsletterMasterCreate: "marketing.newsletter_factory.master.create",
  marketingNewsletterMasterApprove: "marketing.newsletter_factory.master.approve",
  marketingNewsletterFactoryGenerate: "marketing.newsletter_factory.generate",
  marketingNewsletterLocalOverride: "marketing.newsletter_factory.local_override"
} as const;

export type AuditAction = (typeof auditActions)[keyof typeof auditActions] | (string & {});

const actionPattern = /^[a-z][a-z0-9]*(?:\.[a-z][a-z0-9]*)+$/;

export function assertAuditAction(action: string) {
  if (!actionPattern.test(action)) {
    throw new Error(
      `Invalid audit action "${action}". Use stable dot-case names such as "record.update".`
    );
  }
}
