import { AiOutputError, defineAiTask } from "@raring2go/ai";

export type ContentDraftInput = {
  brief: string;
  contentType: string;
  territoryName?: string | null;
  /** Present when revising a draft: the current text the model should build on. */
  existing?: { title: string; standfirst?: string | null; body?: string | null } | null;
};

export type ContentDraftOutput = {
  title: string;
  standfirst: string;
  body: string;
  /** Anything the writer should check: facts the brief did not supply and the model did not invent. */
  notes: string;
};

const LIMITS = { title: 140, standfirst: 320, body: 8_000, notes: 600 } as const;

/** Output is plain text: no HTML or markup ever reaches a content record from a model. */
function plain(value: unknown, max: number, field: string, required: boolean) {
  if (value === undefined || value === null || value === "") {
    if (required) throw new AiOutputError(`The draft is missing its ${field}.`);
    return "";
  }
  if (typeof value !== "string") throw new AiOutputError(`The draft's ${field} was not text.`);
  const text = value
    .replace(/<[^>]*>/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .trim();
  if (required && !text) throw new AiOutputError(`The draft is missing its ${field}.`);
  return text.length > max ? text.slice(0, max).trimEnd() : text;
}

export function normaliseContentDraft(raw: unknown): ContentDraftOutput {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new AiOutputError("The AI did not return a draft in the expected shape.");
  }
  const record = raw as Record<string, unknown>;
  return {
    title: plain(record.title, LIMITS.title, "title", true),
    standfirst: plain(record.standfirst, LIMITS.standfirst, "standfirst", false),
    body: plain(record.body, LIMITS.body, "body", true),
    notes: plain(record.notes, LIMITS.notes, "notes", false)
  };
}

/**
 * The content-creation workflow: brief in, a draft article out. When the existing
 * Raring2go content GPT is exposed as a service (AI_WORKFLOW_CONTENT_DRAFT_URL), the runner
 * routes here to it with `structuredInput`; otherwise the built-in prompt is used. Either
 * way the output goes through the same validation, and a person accepts or rejects it.
 */
export const contentDraftTask = defineAiTask<ContentDraftInput, ContentDraftOutput>({
  key: "content.draft",
  promptVersion: "content-draft.v1",
  purpose: "Draft a content item from a brief",
  risk: "low",
  approval: "review",
  capability: { module: "content.ai", action: "generate" },
  maxTokens: 1800,
  system:
    "You are an editor for Raring2go!, a UK network of local family magazines and websites. " +
    "Write warm, practical, concrete copy for parents. British English. " +
    "Never invent facts: no dates, prices, venues, opening times, names, quotes or links that are not in the brief. " +
    "If the brief lacks something a reader would need, write around it and list what to confirm in `notes`. " +
    "Respond with ONLY a JSON object of the exact shape " +
    '{"title": string, "standfirst": string, "body": string, "notes": string} ' +
    "(no markdown fences, no preamble). Plain text only: no HTML. Separate paragraphs in `body` with a blank line.",
  buildUserPrompt: (input) =>
    `Content type: ${input.contentType}\n` +
    (input.territoryName ? `Territory: ${input.territoryName}\n` : "") +
    (input.existing
      ? `Current draft to improve:\nTitle: ${input.existing.title}\nStandfirst: ${input.existing.standfirst ?? ""}\nBody:\n${(input.existing.body ?? "").slice(0, 4000)}\n\n`
      : "") +
    `Brief: ${input.brief.slice(0, 3000)}`,
  parse: (text) => {
    let parsed: unknown;
    try {
      parsed = JSON.parse(text.trim().replace(/^```(?:json)?\s*|\s*```$/g, ""));
    } catch {
      throw new AiOutputError("The AI did not return a usable draft. Try rephrasing the brief.");
    }
    return normaliseContentDraft(parsed);
  },
  fromStructured: (raw) => normaliseContentDraft(raw),
  structuredInput: (input) => ({ brief: input.brief, contentType: input.contentType, territory: input.territoryName ?? null, existing: input.existing ?? null }),
  deterministic: (input) => ({
    title: input.existing?.title ?? (input.brief.trim().slice(0, 80) || "Untitled draft"),
    standfirst: `A draft about ${input.brief.trim().slice(0, 100)}.`,
    body: `${input.brief.trim()}\n\nThis is a placeholder draft generated without an AI model. Replace it with real copy.`,
    notes: "Generated by the deterministic development provider."
  }),
  summariseInput: (input) => ({ brief: input.brief, contentType: input.contentType, territory: input.territoryName ?? null, revising: Boolean(input.existing) }),
  sources: (input) => (input.existing ? [{ type: "content_item_draft", label: input.existing.title }] : [])
});
