import { createHash } from "node:crypto";
import { AiOutputError, defineAiTask } from "@raring2go/ai";
import { auditActions } from "@raring2go/audit";
import type { RecordAuditEventInput } from "@raring2go/audit";
import { evaluatePermission } from "@raring2go/permissions";
import type { PermissionData } from "@raring2go/permissions";

// ---- Task contract --------------------------------------------------------------------

export type EventDiscoverInput = {
  territoryId: string;
  territoryName: string;
  /** Inclusive date range, YYYY-MM-DD. */
  from: string;
  to: string;
  interests: string[];
  maxResults: number;
};

export type RawDiscoveredEvent = Record<string, unknown>;
export type EventDiscoverOutput = { events: RawDiscoveredEvent[] };

const MAX_RAW_EVENTS = 50;

/**
 * Finds family events for a territory and date range. `externalOnly`: a bare model has no
 * web access and would invent events, so this only runs through the existing events-finding
 * workflow (AI_WORKFLOW_EVENTS_DISCOVER_URL). The deterministic provider returns clearly
 * labelled samples so the queue can be exercised in development.
 */
export const eventsDiscoverTask = defineAiTask<EventDiscoverInput, EventDiscoverOutput>({
  key: "events.discover",
  promptVersion: "events-discover.v1",
  purpose: "Discover family events for a territory",
  risk: "low",
  // Informational: each suggestion is individually approved or rejected in the queue.
  approval: "none",
  capability: { module: "content.event_suggestion", action: "discover" },
  maxTokens: 1,
  externalOnly: true,
  system: "Events are discovered by the configured events-finding workflow, not a built-in prompt.",
  buildUserPrompt: () => "",
  parse: () => {
    throw new AiOutputError("Event discovery runs only through its configured workflow.");
  },
  structuredInput: (input) => ({
    territory: input.territoryName,
    territoryId: input.territoryId,
    from: input.from,
    to: input.to,
    interests: input.interests,
    maxResults: input.maxResults
  }),
  fromStructured: (raw) => {
    const events = raw && typeof raw === "object" ? (raw as { events?: unknown }).events : undefined;
    if (!Array.isArray(events)) {
      throw new AiOutputError("The events workflow did not return a list of events.");
    }
    return {
      events: events.slice(0, MAX_RAW_EVENTS).filter((entry): entry is RawDiscoveredEvent => Boolean(entry) && typeof entry === "object" && !Array.isArray(entry))
    };
  },
  deterministic: (input) => {
    const start = new Date(`${input.from}T10:00:00Z`);
    const day = (offset: number) => new Date(start.getTime() + offset * 86_400_000).toISOString();
    return {
      events: [1, 2, 3].map((n) => ({
        title: `[Sample] Family fun day ${n} in ${input.territoryName}`,
        startsAt: day(n),
        venue: `Sample venue ${n}`,
        url: `https://events.example.test/${input.territoryId}/sample-${n}`,
        summary: "Sample event generated by the deterministic development provider.",
        sourceContext: "Deterministic development sample: not a real event."
      }))
    };
  },
  summariseInput: (input) => ({ territory: input.territoryName, from: input.from, to: input.to, interests: input.interests, maxResults: input.maxResults }),
  sources: (input) => [{ type: "territory", id: input.territoryId, label: input.territoryName }]
});

// ---- Validation -----------------------------------------------------------------------

export type EventCandidate = {
  title: string;
  startsAt: Date;
  endsAt: Date | null;
  venue: string | null;
  summary: string | null;
  sourceUrl: string;
  sourceContext: string;
};

export type RejectedCandidate = { index: number; reason: string };

const TRACKING_PARAMS = /^(utm_|fbclid|gclid|mc_|ref$|ref_)/i;
const PRIVATE_HOST = /^(localhost|.*\.local|.*\.internal|.*\.localhost)$/i;
const MAX_EVENT_DAYS = 7;

function plain(value: unknown, max: number): string {
  return typeof value === "string" ? value.replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim().slice(0, max) : "";
}

/** Public http(s) URL without credentials, tracking parameters or fragment; otherwise undefined. */
export function canonicaliseUrl(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  let url: URL;
  try {
    url = new URL(value.trim());
  } catch {
    return undefined;
  }
  if (url.protocol !== "https:" && url.protocol !== "http:") return undefined;
  if (url.username || url.password) return undefined;
  if (PRIVATE_HOST.test(url.hostname) || /^[\d.]+$/.test(url.hostname) || url.hostname.includes(":")) return undefined;
  if (!url.hostname.includes(".")) return undefined;

  url.hash = "";
  for (const key of [...url.searchParams.keys()]) {
    if (TRACKING_PARAMS.test(key)) url.searchParams.delete(key);
  }
  url.hostname = url.hostname.toLowerCase();
  const text = url.toString();
  return text.endsWith("/") && url.pathname === "/" && !url.search ? text.slice(0, -1) : text.replace(/\/(\?|$)/, "$1");
}

function parseDate(value: unknown): Date | undefined {
  if (typeof value !== "string" || !value.trim()) return undefined;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? undefined : date;
}

export function validateEventCandidates(
  raw: RawDiscoveredEvent[],
  range: { from: string; to: string; now: Date }
): { valid: EventCandidate[]; rejected: RejectedCandidate[] } {
  const rangeStart = new Date(`${range.from}T00:00:00Z`);
  const rangeEnd = new Date(`${range.to}T23:59:59.999Z`);
  const earliest = new Date(Math.max(rangeStart.getTime(), range.now.getTime()));
  const valid: EventCandidate[] = [];
  const rejected: RejectedCandidate[] = [];

  raw.forEach((entry, index) => {
    const reject = (reason: string) => rejected.push({ index, reason });
    const title = plain(entry.title, 140);
    if (title.length < 3) return reject("missing title");

    const startsAt = parseDate(entry.startsAt);
    if (!startsAt) return reject("missing or invalid start date");
    if (startsAt < earliest) return reject("starts in the past or before the requested range");
    if (startsAt > rangeEnd) return reject("starts after the requested range");

    let endsAt: Date | null = null;
    if (entry.endsAt !== undefined && entry.endsAt !== null && entry.endsAt !== "") {
      const parsed = parseDate(entry.endsAt);
      if (!parsed || parsed < startsAt || parsed.getTime() - startsAt.getTime() > MAX_EVENT_DAYS * 86_400_000) return reject("invalid end date");
      endsAt = parsed;
    }

    const sourceUrl = canonicaliseUrl(entry.url);
    if (!sourceUrl) return reject("missing or unusable source URL");

    const sourceContext = plain(entry.sourceContext, 500);
    if (sourceContext.length < 10) return reject("missing source context");

    valid.push({
      title,
      startsAt,
      endsAt,
      venue: plain(entry.venue, 140) || null,
      summary: plain(entry.summary, 400) || null,
      sourceUrl,
      sourceContext
    });
  });

  return { valid, rejected };
}

// ---- Duplicate detection --------------------------------------------------------------

const STOP_WORDS = new Set(["the", "a", "an", "at", "in", "on", "for", "and", "of", "to", "with"]);

function normaliseText(value: string | null | undefined) {
  return (value ?? "").toLowerCase().replace(/[^a-z0-9 ]+/g, " ").replace(/\s+/g, " ").trim();
}

const tokens = (value: string) => new Set(normaliseText(value).split(" ").filter((word) => word && !STOP_WORDS.has(word)));

function jaccard(a: Set<string>, b: Set<string>) {
  if (a.size === 0 || b.size === 0) return 0;
  let shared = 0;
  for (const word of a) if (b.has(word)) shared += 1;
  return shared / (a.size + b.size - shared);
}

const dayOf = (date: Date) => date.toISOString().slice(0, 10);

export function dedupeKeyFor(candidate: Pick<EventCandidate, "title" | "startsAt" | "venue">) {
  return createHash("sha1").update(`${normaliseText(candidate.title)}|${dayOf(candidate.startsAt)}|${normaliseText(candidate.venue)}`).digest("hex");
}

export type KnownEvent = { id: string; kind: "suggestion" | "content"; title: string; startsAt: Date | null; sourceUrl?: string | null; dedupeKey?: string | null };

/** Same key, same canonical URL, or the same day with a near-identical title. */
export function findDuplicate(candidate: EventCandidate, known: KnownEvent[]): KnownEvent | undefined {
  const key = dedupeKeyFor(candidate);
  const candidateTokens = tokens(candidate.title);
  return known.find((other) => {
    if (other.dedupeKey && other.dedupeKey === key) return true;
    if (other.sourceUrl && canonicaliseUrl(other.sourceUrl) === candidate.sourceUrl) return true;
    return Boolean(other.startsAt && dayOf(other.startsAt) === dayOf(candidate.startsAt) && jaccard(candidateTokens, tokens(other.title)) >= 0.8);
  });
}

// ---- Queue ----------------------------------------------------------------------------

export type EventSuggestionStatus = "pending" | "approved" | "rejected";

export type EventSuggestionRecord = {
  id: string;
  territoryId: string;
  aiRunId: string | null;
  title: string;
  startsAt: Date;
  endsAt: Date | null;
  venue: string | null;
  summary: string | null;
  sourceUrl: string;
  sourceContext: string;
  dedupeKey: string;
  status: EventSuggestionStatus;
  contentItemId: string | null;
  decidedByUserId: string | null;
  decidedAt: Date | null;
  decisionNote: string | null;
  createdAt: Date;
};

export type NewEventSuggestion = Omit<EventSuggestionRecord, "id" | "status" | "contentItemId" | "decidedByUserId" | "decidedAt" | "decisionNote" | "createdAt">;

export type EventSuggestionStore = {
  /** Inserts new suggestions; rows whose (territory, dedupeKey) already exist are skipped. Returns only the created rows. */
  insertMany(rows: NewEventSuggestion[], now: Date): Promise<EventSuggestionRecord[]>;
  get(id: string): Promise<EventSuggestionRecord | undefined>;
  list(filter: { territoryId?: string; status?: EventSuggestionStatus; limit?: number }): Promise<EventSuggestionRecord[]>;
  /** Decides a pending suggestion exactly once. */
  decide(id: string, decision: { status: "approved" | "rejected"; userId: string; note: string | null; contentItemId?: string | null }, now: Date): Promise<EventSuggestionRecord | undefined>;
};

export const eventSuggestionCapabilities = {
  view: { module: "content.event_suggestion", action: "view" },
  discover: { module: "content.event_suggestion", action: "discover" },
  decide: { module: "content.event_suggestion", action: "decide" }
} as const;

export type EventActorContext = { userId: string; organisationId?: string | null; territoryId?: string | null };
export type EventAuditRecorder = { record: (input: RecordAuditEventInput) => Promise<unknown> };

export class EventAccessError extends Error {
  constructor(message = "You do not have access to these event suggestions.") {
    super(message);
    this.name = "EventAccessError";
  }
}

export class EventStateError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EventStateError";
  }
}

function allowed(context: EventActorContext, permissions: PermissionData, capability: keyof typeof eventSuggestionCapabilities, territoryId?: string) {
  const { module, action } = eventSuggestionCapabilities[capability];
  return evaluatePermission({ userId: context.userId, module, action, ...(territoryId ? { resource: { territoryId } } : {}) }, permissions).allowed;
}

export function requireEventPermission(context: EventActorContext, permissions: PermissionData, capability: keyof typeof eventSuggestionCapabilities, territoryId: string) {
  if (!allowed(context, permissions, capability, territoryId)) {
    throw new EventAccessError(`Missing permission ${eventSuggestionCapabilities[capability].module}.${eventSuggestionCapabilities[capability].action} for this territory.`);
  }
}

export type IngestResult = { created: EventSuggestionRecord[]; duplicates: number; invalid: RejectedCandidate[] };

/**
 * Turns raw workflow output into pending suggestions: validates each candidate, drops
 * duplicates (of earlier suggestions in any status, existing event content, or each other)
 * and stores the rest. Nothing here creates or publishes content.
 */
export async function ingestDiscoveredEvents(
  context: EventActorContext,
  permissions: PermissionData,
  audit: EventAuditRecorder,
  store: EventSuggestionStore,
  existingEventContent: KnownEvent[],
  input: { territoryId: string; aiRunId: string | null; rawEvents: RawDiscoveredEvent[]; from: string; to: string; maxResults: number },
  now: Date = new Date()
): Promise<IngestResult> {
  requireEventPermission(context, permissions, "discover", input.territoryId);

  const { valid, rejected } = validateEventCandidates(input.rawEvents, { from: input.from, to: input.to, now });
  const earlier = await store.list({ territoryId: input.territoryId, limit: 500 });
  const known: KnownEvent[] = [
    ...existingEventContent,
    ...earlier.map((row): KnownEvent => ({ id: row.id, kind: "suggestion", title: row.title, startsAt: row.startsAt, sourceUrl: row.sourceUrl, dedupeKey: row.dedupeKey }))
  ];

  const fresh: NewEventSuggestion[] = [];
  let duplicates = 0;

  for (const candidate of valid) {
    if (fresh.length >= input.maxResults) break;
    if (findDuplicate(candidate, known)) {
      duplicates += 1;
      continue;
    }
    const dedupeKey = dedupeKeyFor(candidate);
    fresh.push({ ...candidate, territoryId: input.territoryId, aiRunId: input.aiRunId, dedupeKey });
    // Later candidates in the same batch are checked against this one too.
    known.push({ id: dedupeKey, kind: "suggestion", title: candidate.title, startsAt: candidate.startsAt, sourceUrl: candidate.sourceUrl, dedupeKey });
  }

  const created = fresh.length > 0 ? await store.insertMany(fresh, now) : [];

  await audit.record({
    action: auditActions.aiGenerate,
    actor: { type: "human", userId: context.userId },
    entity: { type: "event_discovery", id: input.aiRunId ?? undefined },
    scope: { territoryId: input.territoryId },
    metadata: { task: "events.discover", received: input.rawEvents.length, created: created.length, duplicates, invalid: rejected.length, aiRunId: input.aiRunId }
  });

  return { created, duplicates, invalid: rejected };
}

export async function listEventSuggestionsForActor(
  context: EventActorContext,
  permissions: PermissionData,
  store: EventSuggestionStore,
  filter: { status?: EventSuggestionStatus; limit?: number } = {}
): Promise<EventSuggestionRecord[]> {
  const network = allowed(context, permissions, "view");
  if (!network && !(context.territoryId && allowed(context, permissions, "view", context.territoryId))) {
    throw new EventAccessError("Missing permission content.event_suggestion.view.");
  }
  const rows = await store.list({ ...filter, ...(network ? {} : { territoryId: context.territoryId! }) });
  return rows.filter((row) => network || allowed(context, permissions, "view", row.territoryId));
}

export async function rejectEventSuggestion(
  context: EventActorContext,
  permissions: PermissionData,
  audit: EventAuditRecorder,
  store: EventSuggestionStore,
  suggestionId: string,
  note: string | null,
  now: Date = new Date()
): Promise<EventSuggestionRecord> {
  const suggestion = await store.get(suggestionId);
  if (!suggestion || !allowed(context, permissions, "decide", suggestion.territoryId)) {
    throw new EventAccessError(suggestion ? "Missing permission content.event_suggestion.decide for this territory." : "Event suggestion not found.");
  }
  if (suggestion.status !== "pending") throw new EventStateError(`This suggestion is already ${suggestion.status}.`);

  const decided = await store.decide(suggestionId, { status: "rejected", userId: context.userId, note: note?.trim().slice(0, 500) || null }, now);
  if (!decided) throw new EventStateError("This suggestion was decided by someone else first.");

  await audit.record({
    action: auditActions.aiReject,
    actor: { type: "human", userId: context.userId },
    entity: { type: "event_suggestion", id: suggestion.id },
    scope: { territoryId: suggestion.territoryId },
    before: { status: "pending" },
    after: { status: "rejected" },
    metadata: { title: suggestion.title, sourceUrl: suggestion.sourceUrl, note: decided.decisionNote, aiRunId: suggestion.aiRunId }
  });
  return decided;
}

/** Read-and-check step shared by approval: returns the suggestion if the actor may approve it. */
export async function requireApprovableSuggestion(context: EventActorContext, permissions: PermissionData, store: EventSuggestionStore, suggestionId: string) {
  const suggestion = await store.get(suggestionId);
  if (!suggestion || !allowed(context, permissions, "decide", suggestion.territoryId)) {
    throw new EventAccessError(suggestion ? "Missing permission content.event_suggestion.decide for this territory." : "Event suggestion not found.");
  }
  if (suggestion.status !== "pending") throw new EventStateError(`This suggestion is already ${suggestion.status}.`);
  return suggestion;
}

export async function recordEventApproval(
  context: EventActorContext,
  audit: EventAuditRecorder,
  store: EventSuggestionStore,
  suggestion: EventSuggestionRecord,
  input: { contentItemId: string; note: string | null },
  now: Date = new Date()
): Promise<EventSuggestionRecord> {
  const decided = await store.decide(suggestion.id, { status: "approved", userId: context.userId, note: input.note?.trim().slice(0, 500) || null, contentItemId: input.contentItemId }, now);
  if (!decided) throw new EventStateError("This suggestion was decided by someone else first.");

  await audit.record({
    action: auditActions.aiApprove,
    actor: { type: "human", userId: context.userId },
    entity: { type: "event_suggestion", id: suggestion.id },
    scope: { territoryId: suggestion.territoryId },
    before: { status: "pending" },
    after: { status: "approved", contentItemId: input.contentItemId },
    metadata: { title: suggestion.title, sourceUrl: suggestion.sourceUrl, aiRunId: suggestion.aiRunId }
  });
  return decided;
}
